name: CI

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          repository: 'https://github.com/libplctag/libplctag'

      - uses: nttld/setup-ndk@v1
        id: setup-ndk
        with:
          ndk-version: r21d

      - name: Create build directory
        run: rm -rf ${{ env.BUILD }}; mkdir -p ${{ env.BUILD }}

      - name: Configure CMake
        run: cd ${{ env.BUILD }}; cmake -DCMAKE_BUILD_TYPE=Release -DCMAKE_TOOLCHAIN_FILE=${{ steps.setup-ndk.outputs.ndk-path }}/build/cmake/android.toolchain.cmake -DANDROID_ABI=arm64-v8a ..
  # -DANDROID_NATIVE_API_LEVEL=android-N-MR1

      - name: Build
        run: cd ${{ env.BUILD }}; cmake --build .

      - name: Upload ZIP artifact
        uses: actions/upload-artifact@v1
        with:
          name: ${{ env.ARTIFACT }}
          path: ${{ env.DIST }}
