name: build

on:
  workflow_dispatch:
    inputs:
      VERSION:
        description: 'Version number string (e.g. 2.3.4)'
        required: true

jobs:
  build:
    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        abi:
          - armeabi-v7a
          - arm64-v8a
          - x86
          - x86_64
          
    env:
      BUILD: "${{ github.workspace }}/build"
      DIST: "${{ github.workspace }}/build/bin_dist"

    steps:
      - uses: actions/checkout@v2
        with:
          repository: 'libplctag/libplctag'

      - uses: nttld/setup-ndk@v1
        id: setup-ndk
        with:
          ndk-version: r21d

      - name: Create build directory
        run: rm -rf ${{ env.BUILD }}; mkdir -p ${{ env.BUILD }}

      - name: Configure CMake
        run: cd ${{ env.BUILD }}; cmake -DCMAKE_BUILD_TYPE=Release -DCMAKE_TOOLCHAIN_FILE=${{ steps.setup-ndk.outputs.ndk-path }}/build/cmake/android.toolchain.cmake -DANDROID_ABI=${{ matrix.abi }} ..

      - name: Build
        run: cd ${{ env.BUILD }}; cmake --build .

      - name: Upload ZIP artifact
        uses: actions/upload-artifact@v1
        with:
          name: "libplctag_${{ github.event.inputs.VERSION }}_android_${{ matrix.abi }}"
          path: ${{ env.DIST }}
